branches:
  except:
  - release

sudo: required
dist: trusty

matrix:
  include:
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
      language: cpp
      osx_image: xcode8.2
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
      language: cpp
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
      language: cpp
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
    - env: BUILD_NAME=android
      language: android


android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


env:
  global:
  #encrypted PRORAB_GIT_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "TVpaDORaVW+gRQxHIsyG2XTosxYBe3EbH2HMGkT0mF5c2iXcqRY/i387Mm50gnaf4PGRQexv4DyikMbL8bbYvhz8/P/nr/cXQzodIspRw/3dHzRSQUDUp9mQN3cApyySBX4PqwlNQokiJ9Z6KbaSqDRbJT7scVnjPpR+R0j9qw+RbX7tBxRs6d5KRECT8ojRBJs925uKeHSSn9/MV+n0tAfyPrg2EgrP5xaHDXawvrHLEpIYo9Ek2DwKBp7YxIp3UhaY7/EuVV5u2R+Y4U3Ynrwaunni54Wk3hFkGFx24bxMNcF+1Ihxr48o2AQy4LvLQ9uX8T34brgTwwdN4QF0cBjnXABibS3frSCDbL+D931Wxg+hCnpFRnm0h7O8UUI5bvArvx6nWD9rW5dR21RoLicz4zvGfuUSvOKUl47Lwavgs3f6w4nyl0a/F16fCCtKK6cSXCNtsK44+8kGCGdW7hl+Sv9417DFjx1uGxnNpO9x1qsmqRvNG32yKqWu+IZzDv833l0G4SksNu6GV2Qkc/zq3acpXKRkp8Pn/fsFUs5M87L/pOh6mamlbLdpvGWJ8059IEWfblFvPFcx2yH3pXdMVrid7uBSdrRLLGP7FsDEI/7XcMc+V29I2KztT0AVSjSkDEldkLo+7dLtfkkZ9c9VYILeMc4ESY7+8LHLfM0="
  - PRORAB_GIT_USERNAME=igagis
  - linuxDependencies="debhelper lintian pkg-config prorab doxygen libkolme-dev libmorda-dev"



before_install:
- if [ "$BUILD_NAME" == "ios" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential stretch /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
    sudo prorab-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y libgles2-mesa-dev &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi


before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -O &&
      unzip ./android-ndk-r14b-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r14b-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r14b &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi
  - if [ "$BUILD_NAME" == "ios" ]; then
      curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
      chmod +x XcodeProjAdder &&
      (cd ios && ../XcodeProjAdder -XCP tests.xcodeproj -SCSV `echo $(find ../src -type f -name *.cpp) | sed -n -e 's/ /,/gp'`);
    fi

script:
- if [ "$BUILD_NAME" == "ios" ]; then
    set -o pipefail &&
    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
            | sed -e "s/export PATH=[^ ]*/export PATH=.../g"
            | sed -e "s/[^ ]*\/clang /clang /g"
            | sed -e "s/\(-[IWfFL]\)[^ ]*/% /g"
            | sed -e "s/-isystem [^ ]*/%/g"
            | sed -e "s/-include [^ ]*/%/g"
            | sed -e "s/-MF [^ ]*/-MF .../g"
            | sed -e "s/--serialize-diagnostics [^ ]*/%/g"
            | sed -e "s/-o [^ ]*/%/g"
            | sed -e "s/-iquote [^ ]*/%/g"
            | sed -e "s/-isysroot [^ ]*/%/g";
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d stretch-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && prorab-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.pom.in &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi
  

before_deploy:
  - prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` travis_bintray_*.json.in


deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "i69PiIo6waETMrstLNuHt6UrO9vQcyzmftBkujxpodyjVsTzJ1le7KHFBrh9CcgOz+2qkjOSLPkHkaCi9mlHnhMHwHt0OwHxl943dgdnUQqRM2pY+IeDnaP1BRrOJJxy1cDkq35Sj1lRw1zOG+jMtFS4WWKsGqYspRxHAzNdseSfQpEGNWqpjE4Nfc4xJHyP95AF/mzVbaykr5zI3vTW3b4nROK3p7woUqQcj7/jRLJdmGweldkvznbrZgMWUrBd+t7GGkNIa5rg7clo3NcfNXpLoX7rdI1fHkRec0uJFWAomMBvvFxCjH6jo1jTx1VNKYhXK5P7Ze4iXDXZ8i/5BPTDyBkDbOjMby77fcEYe//2C2ozpNL4Qmd+f3P99rSPwaTURV8Gc2JQiJG4TSN+BMRLrcmV/8BcT2v5XusY2JchmYo23puKh61Uqnzm2jsB75Yyl4vyukyUdd1k258DIKCtE3PBcsnN0QH/QKsk7birafPbUx1UDK4GSERUNZb0kPGJV7EUsSTNi2O5ygKy43u0TmACCN1buhC7+PpnRrqUhr3iGkdvPU8u45abPlDPXbWNDFcZiHuvDRL7aJUvbZGGfRNRbZz5XTfg8zqMGJdNobUyiYL9+e67iYKecDwigfvtK/9L/5Qjfa+0KjraBf1FKkyc2I4XVQam/YU3Miw="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = ubuntu
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "i69PiIo6waETMrstLNuHt6UrO9vQcyzmftBkujxpodyjVsTzJ1le7KHFBrh9CcgOz+2qkjOSLPkHkaCi9mlHnhMHwHt0OwHxl943dgdnUQqRM2pY+IeDnaP1BRrOJJxy1cDkq35Sj1lRw1zOG+jMtFS4WWKsGqYspRxHAzNdseSfQpEGNWqpjE4Nfc4xJHyP95AF/mzVbaykr5zI3vTW3b4nROK3p7woUqQcj7/jRLJdmGweldkvznbrZgMWUrBd+t7GGkNIa5rg7clo3NcfNXpLoX7rdI1fHkRec0uJFWAomMBvvFxCjH6jo1jTx1VNKYhXK5P7Ze4iXDXZ8i/5BPTDyBkDbOjMby77fcEYe//2C2ozpNL4Qmd+f3P99rSPwaTURV8Gc2JQiJG4TSN+BMRLrcmV/8BcT2v5XusY2JchmYo23puKh61Uqnzm2jsB75Yyl4vyukyUdd1k258DIKCtE3PBcsnN0QH/QKsk7birafPbUx1UDK4GSERUNZb0kPGJV7EUsSTNi2O5ygKy43u0TmACCN1buhC7+PpnRrqUhr3iGkdvPU8u45abPlDPXbWNDFcZiHuvDRL7aJUvbZGGfRNRbZz5XTfg8zqMGJdNobUyiYL9+e67iYKecDwigfvtK/9L/5Qjfa+0KjraBf1FKkyc2I4XVQam/YU3Miw="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "i69PiIo6waETMrstLNuHt6UrO9vQcyzmftBkujxpodyjVsTzJ1le7KHFBrh9CcgOz+2qkjOSLPkHkaCi9mlHnhMHwHt0OwHxl943dgdnUQqRM2pY+IeDnaP1BRrOJJxy1cDkq35Sj1lRw1zOG+jMtFS4WWKsGqYspRxHAzNdseSfQpEGNWqpjE4Nfc4xJHyP95AF/mzVbaykr5zI3vTW3b4nROK3p7woUqQcj7/jRLJdmGweldkvznbrZgMWUrBd+t7GGkNIa5rg7clo3NcfNXpLoX7rdI1fHkRec0uJFWAomMBvvFxCjH6jo1jTx1VNKYhXK5P7Ze4iXDXZ8i/5BPTDyBkDbOjMby77fcEYe//2C2ozpNL4Qmd+f3P99rSPwaTURV8Gc2JQiJG4TSN+BMRLrcmV/8BcT2v5XusY2JchmYo23puKh61Uqnzm2jsB75Yyl4vyukyUdd1k258DIKCtE3PBcsnN0QH/QKsk7birafPbUx1UDK4GSERUNZb0kPGJV7EUsSTNi2O5ygKy43u0TmACCN1buhC7+PpnRrqUhr3iGkdvPU8u45abPlDPXbWNDFcZiHuvDRL7aJUvbZGGfRNRbZz5XTfg8zqMGJdNobUyiYL9+e67iYKecDwigfvtK/9L/5Qjfa+0KjraBf1FKkyc2I4XVQam/YU3Miw="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "i69PiIo6waETMrstLNuHt6UrO9vQcyzmftBkujxpodyjVsTzJ1le7KHFBrh9CcgOz+2qkjOSLPkHkaCi9mlHnhMHwHt0OwHxl943dgdnUQqRM2pY+IeDnaP1BRrOJJxy1cDkq35Sj1lRw1zOG+jMtFS4WWKsGqYspRxHAzNdseSfQpEGNWqpjE4Nfc4xJHyP95AF/mzVbaykr5zI3vTW3b4nROK3p7woUqQcj7/jRLJdmGweldkvznbrZgMWUrBd+t7GGkNIa5rg7clo3NcfNXpLoX7rdI1fHkRec0uJFWAomMBvvFxCjH6jo1jTx1VNKYhXK5P7Ze4iXDXZ8i/5BPTDyBkDbOjMby77fcEYe//2C2ozpNL4Qmd+f3P99rSPwaTURV8Gc2JQiJG4TSN+BMRLrcmV/8BcT2v5XusY2JchmYo23puKh61Uqnzm2jsB75Yyl4vyukyUdd1k258DIKCtE3PBcsnN0QH/QKsk7birafPbUx1UDK4GSERUNZb0kPGJV7EUsSTNi2O5ygKy43u0TmACCN1buhC7+PpnRrqUhr3iGkdvPU8u45abPlDPXbWNDFcZiHuvDRL7aJUvbZGGfRNRbZz5XTfg8zqMGJdNobUyiYL9+e67iYKecDwigfvtK/9L/5Qjfa+0KjraBf1FKkyc2I4XVQam/YU3Miw="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
